syswonder/ruxos

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/test.yml, rust-toolchain.toml
I lock the version of rustc to 1.74.0(nightly-2023-09-01) to pass the CI.
=> lock the version of rustc to 1.74.0

api/axfeat/Cargo.toml, apps/c/filetest/features.txt, apps/c/iperf/features.txt, apps/c/redis/features.txt, apps/c/sqlite3/features.txt, apps/fs/shell/Cargo.toml, modules/ax9p/src/drv.rs, modules/ax9p/src/fs.rs, modules/axfs/src/lib.rs, modules/axfs/src/root.rs, modules/axruntime/Cargo.toml, modules/axruntime/src/lib.rs, ulib/axstd/Cargo.toml
1. Fix 9p buffer bugs in `tread()`,`treaddir()`,`u_treaddir()` and `twrite()`.
2. Add feature `blkfs` to make it possible to mount `9pfs` or ramfs as rootfs.
=> fix buffer bugs in 9pfs and add `blkfs` feature

apps/c/nginx/features.txt, apps/c/redis/features.txt
Since wasm PR #40 adds `signal` feature in `ruxmusl`, signal-related APIs are not accessible if `signal` feature is not specified in Redis/Nginx, which may cause unknown bugs. 
This PR just adds `signal` feature in these two apps.
=> fix signal bug in Redis/Nginx

apps/c/wamr/CMakeLists.txt, apps/c/wamr/README.md, apps/c/wamr/axbuild.mk, apps/c/wamr/wamr.patch
I have built WAMR through cmake, instead of specifying each source file manually.
Users can configure some options using -D in cmake command, which makes it convenient to select optional function of WAMR.
It is the basis for the next step of adding support for WASI-NN.
=> using cmake to build WAMR

modules/ruxhal/src/platform/aarch64_raspi/mem.rs, modules/ruxhal/src/platform/aarch64_raspi/mod.rs, modules/ruxhal/src/platform/aarch64_raspi/mp.rs, modules/ruxhal/src/platform/mod.rs, platforms/aarch64-raspi4.toml, scripts/make/raspi4.mk, tools/.gitignore, tools/raspi4/common/docker.mk, tools/raspi4/common/format.mk, tools/raspi4/common/operating_system.mk, tools/raspi4/common/serial/minipush.rb, tools/raspi4/common/serial/minipush/progressbar_patch.rb, tools/raspi4/common/serial/miniterm.rb
Added some scripts to support Raspberry Pi
=> add support for Raspberry Pi

api/ruxos_posix_api/Cargo.toml, api/ruxos_posix_api/src/imp/fs.rs, api/ruxos_posix_api/src/imp/getrandom.rs, api/ruxos_posix_api/src/imp/mod.rs, api/ruxos_posix_api/src/lib.rs, modules/ruxfs/src/fops.rs, platforms/aarch64-qemu-virt.toml, platforms/riscv64-qemu-virt.toml, platforms/x86_64-qemu-q35.toml, scripts/make/qemu.mk, ulib/ruxlibc/Cargo.toml, ulib/ruxlibc/include/sys/random.h, ulib/ruxlibc/src/lib.rs, ulib/ruxlibc/src/rand.rs, ulib/ruxmusl/src/aarch64/mod.rs, ulib/ruxmusl/src/aarch64/syscall_id.rs, ulib/ruxmusl/src/x86_64/mod.rs, ulib/ruxmusl/src/x86_64/syscall_id.rs
I have added or modified following syscalls:
* `getrandom`: move random-related functions and feature to posix-api layer from ruxlibc, and add `getrandom` syscall.
* `pread` and `preadv`: add `pread` and `preadv` syscalls, but only implemented for `File` as `FileLike` trait.
* `readlinkat`: modify the implementation of `readlinkat` to return `EINVAL` directly, because we don't support symlink currently.
* `openat`: support relative path.
* `fstat`: support getting the stat infomation of a directory by passing its file descriptor.
And there are some other changes:
* expand default memory of qemu to 2G.
* add Cap::EXECUTE to capabilities of Directory::node when directory is opened in any case.
Now wasi-nn is supported in WAMR.
=> Add and modify some syscalls and support wasi-nn in WAMR

Cargo.lock, api/ruxos_posix_api/src/imp/getrandom.rs, crates/driver_pci/Cargo.toml, crates/driver_virtio/Cargo.toml, modules/rux9p/src/drv.rs, modules/rux9p/src/fs.rs, modules/ruxhal/src/platform/aarch64_common/pl011.rs
1. fix bug in function `has_rdrand`, which may cause an endless cycle.
2. fix bugs in 9pfs, which may cause some `net-9p` open fault (for some backend), or a wrong return value when writing.
3. fix bug in pl011, which actually has no handler when irq is enable.
4. improve the performance of 9pfs for read_dir().
=> fix problem in `random-hw`, `9p` and `pl011`.

.gitignore, Cargo.lock, Cargo.toml, Makefile, api/ruxos_posix_api/Cargo.toml, api/ruxos_posix_api/src/imp/pthread/futex.rs, api/ruxos_posix_api/src/imp/pthread/mod.rs, apps/c/libc-bench/axbuild.mk, modules/ruxfutex/Cargo.toml, modules/ruxfutex/src/api.rs, modules/ruxfutex/src/lib.rs, modules/ruxfutex/src/types.rs, modules/ruxhal/src/arch/aarch64/context.rs, modules/ruxruntime/Cargo.toml, modules/ruxruntime/src/lib.rs, modules/ruxtask/src/api.rs, modules/ruxtask/src/task.rs, modules/ruxtask/src/wait_queue.rs, scripts/debug/rust-gdb.sh, scripts/make/build_c.mk, scripts/make/build_musl.mk, scripts/make/cargo.mk, ulib/ruxmusl/src/aarch64/mod.rs, ulib/ruxmusl/src/x86_64/mod.rs
1. Implemented basic futex ops including `FUTEX_WAIT(_BITSET)` and `FUTEX_WAKE(_BITSET)`.
2. Modified `WaitQueue` accordingly to provide more control over wakeup behaviors.
TODO:
1. Move `futex_init` and statics to `ruxruntime`.
2. Put futex-related codes under musl feature.
=> Implemented basic futex operations

api/ruxos_posix_api/src/imp/mmap/api.rs, api/ruxos_posix_api/src/imp/mmap/trap.rs, api/ruxos_posix_api/src/imp/mmap/utils.rs, api/ruxos_posix_api/src/imp/stdio.rs, modules/axnet/src/smoltcp_impl/tcp.rs, modules/ruxhal/src/paging.rs, modules/ruxhal/src/platform/aarch64_common/pl031.rs, ulib/ruxlibc/src/io.rs, ulib/ruxmusl/src/lib.rs, ulib/ruxmusl/src/trap.rs, ulib/ruxmusl/src/x86_64/mod.rs
FIx two problem in mmap and munmap:
1. part of the memory may be released when munmap fails.
2. The semantic error of mmap's MAP_FIXED flag.
and clean warnings in `make clippy` and `make unittest`.
=> fix bugs in mmap and warnings for clippy

apps/c/cpp/axbuild.mk, apps/c/cpp/std_benchmark.patch
I modified c++ benchmark patch to avoid memory allocation failures, which caused by too many iteration counts.
=> modify c++ benchmark

api/ruxos_posix_api/src/imp/fs.rs, api/ruxos_posix_api/src/imp/mmap/api.rs, api/ruxos_posix_api/src/imp/mmap/trap.rs, api/ruxos_posix_api/src/imp/mmap/utils.rs, modules/ruxconfig/defconfig.toml, modules/ruxhal/src/arch/aarch64/trap.rs
fix problems below:
1. mmap with `MAP_FIXED`: If the memory region specified by addr and length overlaps pages of any existing mapping(s), then the overlapped part of the existing mapping(s) will be discarded.
2. After the mmap() call has returned, the file descriptor, fd, can be closed immediately without invalidating the mapping.
3. disable_irq() before syscall handler restores registers, which prevent interruptions when restoring the registers.
=> fix problems in mmap and syscall handler

rust-toolchain.toml
Update rustc version to `nightly-1.76.0` because of some unstable features for `cargo-binutils` dependencies.
=> update rustc version to nightly-1.76.0

Cargo.lock, api/ruxos_posix_api/src/imp/mmap/mod.rs, api/ruxos_posix_api/src/imp/mmap/trap.rs, crates/allocator/Cargo.toml, crates/scheduler/Cargo.toml, modules/ruxhal/src/arch/aarch64/trap.rs, modules/ruxhal/src/arch/x86_64/mod.rs, modules/ruxhal/src/arch/x86_64/trap.rs, modules/ruxhal/src/platform/x86_pc/apic.rs, scripts/make/build_c.mk, scripts/make/build_musl.mk, scripts/make/features.mk, ulib/ruxlibc/Cargo.toml
This PR implements #94 for x86_64. 
Note, both `irq` and `paging` are needed for x86_64 to use fully implemented mmap when SMP is enabled.
=> implement pagefault and tlb_flush for x86_64 to support mmap.

api/ruxos_posix_api/src/imp/fs.rs
- Modified the char_ptr_to_str function to add support for relative paths starting with ".." and '.'
- And renamed it to char_ptr_to_absolute_path
=> Support relative paths

Cargo.lock, Cargo.toml, api/ruxfeat/Cargo.toml, api/ruxos_posix_api/Cargo.toml, api/ruxos_posix_api/build.rs, api/ruxos_posix_api/ctypes.h, api/ruxos_posix_api/src/imp/getrandom.rs, api/ruxos_posix_api/src/imp/ioctl.rs, api/ruxos_posix_api/src/imp/stdio.rs, apps/c/busybox/.gitignore, apps/c/busybox/README.md, apps/c/busybox/axbuild.mk, apps/c/busybox/config_linux.toml, apps/c/busybox/features.txt, apps/c/busybox/main.c, apps/c/dl/axbuild.mk, crates/tty/Cargo.toml, crates/tty/src/buffer.rs, crates/tty/src/constant.rs, crates/tty/src/driver.rs, crates/tty/src/ldisc.rs, crates/tty/src/lib.rs, crates/tty/src/tty.rs, modules/ruxhal/Cargo.toml, modules/ruxhal/src/lib.rs, modules/ruxhal/src/platform/aarch64_common/pl011.rs, modules/ruxruntime/Cargo.toml, modules/ruxruntime/src/lib.rs, scripts/make/build_musl.mk
- add tty support.
- add application busybox.
=> support tty

api/ruxos_posix_api/src/imp/mmap/api.rs, api/ruxos_posix_api/src/imp/mmap/utils.rs, modules/rux9p/src/fs.rs
1. Remove the synchronization operation of mremap when shrinking, which may cause the file to expand #112.
2. Change the alignment logic of mmap to allow non-4K aligned file mappings, which may also cause the file to expand.
3. fix a problem in 9pfs's operation of `rename`, which is an obvious mistake and may cause failure for rename in different format of path.
=> fix bugs in mremap and 9p's rename

modules/rux9p/src/drv.rs
fix problem in issue #132, which causes 9p backend failure.
=> fix 9p backend error for fsync

Cargo.lock, Cargo.toml, crates/spinlock/Cargo.toml, crates/spinlock/src/base.rs, crates/spinlock/src/lib.rs, crates/spinlock/src/strategy.rs, modules/ruxrand/Cargo.toml, modules/ruxrand/src/lib.rs, modules/ruxrand/src/rng.rs, modules/ruxrand/src/spin_rand.rs, modules/ruxruntime/Cargo.toml, modules/ruxruntime/src/lib.rs, modules/ruxruntime/src/mp.rs, modules/ruxtask/Cargo.toml, modules/ruxtask/src/run_queue.rs
1. Modified crates/spinlock to provide support for multiple backoff strategies when encountering lock contention, including exp-backoff and rand-exp-backoff.
2. Modified `BaseSpinLock` in crates/spinlock to support locking with a different guard/backoff type, providing more flexibility.
3. Added a new module `ruxrand` that aims to provide support for the usage of RNGs inside kernel. Currently a per-CPU RNG and support for rand-exp-backoff in spinlock are implemented.
4. Changed the lock type used by `RunQueue`.
=> Implemented various backoffs and per-CPU rng

api/ruxos_posix_api/src/imp/pipe.rs, api/ruxos_posix_api/src/imp/pthread/mod.rs, api/ruxos_posix_api/src/imp/task.rs, api/ruxos_posix_api/src/lib.rs, crates/percpu/src/imp.rs, modules/ruxtask/src/api.rs, modules/ruxtask/src/fs.rs, modules/ruxtask/src/task.rs, ulib/ruxmusl/src/aarch64/mod.rs, ulib/ruxmusl/src/aarch64/syscall_id.rs
1. deadlock when `SMP>1`.
2. wrong judgement for pipe's write end closure.
3. unclosed files when `sys_exit_group` .
=> fix bugs for multiprocess in aarch64.

.github/workflows/build.yml, .github/workflows/test.yml, Cargo.lock, api/ruxos_posix_api/ctypes.h, api/ruxos_posix_api/src/imp/net.rs, crates/axfs_ramfs/src/dir.rs, crates/axfs_ramfs/src/file.rs, crates/axfs_vfs/Cargo.toml, crates/axfs_vfs/src/structs.rs, modules/rux9p/src/drv.rs, modules/rux9p/src/fs.rs, modules/ruxfs/Cargo.toml, modules/ruxfs/src/api/file.rs, modules/ruxfs/src/fs/fatfs.rs, modules/ruxfs/src/lib.rs, modules/ruxfs/src/root.rs, modules/ruxnet/Cargo.toml, modules/ruxnet/src/lib.rs, modules/ruxnet/src/smoltcp_impl/tcp.rs, modules/ruxnet/src/unix.rs
add unix socket ans AF_UNIX type for socket
but not impl SOCK_DGRAM, and use alloced index rather than inode for unixsocket because inode is not impl yet
=> add unixsocket without real inode

api/ruxos_posix_api/src/imp/task.rs
=> Fix null pointer dereference when wstatus is NULL in sys_wait4

api/ruxos_posix_api/src/imp/io_mpx/poll.rs, api/ruxos_posix_api/src/imp/net.rs, api/ruxos_posix_api/src/imp/pipe.rs, api/ruxos_posix_api/src/imp/resources.rs, api/ruxos_posix_api/src/lib.rs, modules/ruxnet/src/unix.rs, ulib/ruxmusl/src/aarch64/mod.rs, ulib/ruxmusl/src/aarch64/syscall_id.rs, ulib/ruxmusl/src/riscv64/mod.rs, ulib/ruxmusl/src/riscv64/syscall_id.rs, ulib/ruxmusl/src/x86_64/mod.rs, ulib/ruxmusl/src/x86_64/syscall_id.rs
Implement the `sys_socketpair` syscall to create a pair of connected UNIX domain sockets (AF_UNIX) for inter-process communication. Similar to pipes, it provides a communication channel between related processes, such as parent-child processes. However, unlike pipes, socket pairs offer more flexibility, supporting full-duplex communication and allowing for more complex messaging. It does not support network communication (e.g., AF_INET or AF_INET6).
There is an test program to check if this syscall works:
```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <unistd.h>
#include <sys/select.h>
// Test if two stream sockets can read and write to each other
void test_stream_rw_each()
{ …
```
=> feat: implement syscall sys_socketpair

api/ruxos_posix_api/src/imp/net.rs, api/ruxos_posix_api/src/imp/stat.rs, api/ruxos_posix_api/src/lib.rs, modules/ruxfs/src/mounts.rs, ulib/ruxmusl/src/aarch64/mod.rs, ulib/ruxmusl/src/aarch64/syscall_id.rs
Motivation:
The RingBuffer is a generic data structure that can be useful in multiple contexts. By extracting it from PipeRingBuffer, we avoid code duplication and make it easier to maintain and test.
Impact:
Existing PipeRingBuffer functionality remains unchanged
New modules can now import and use RingBuffer directly
Add some unit tests for RingBuffer
=> refactor: Extract RingBuffer from PipeRingBuffer for better reusability

api/ruxos_posix_api/src/imp/fs.rs, api/ruxos_posix_api/src/imp/mmap/api.rs, api/ruxos_posix_api/src/imp/mmap/trap.rs, api/ruxos_posix_api/src/imp/mmap/utils.rs, api/ruxos_posix_api/src/lib.rs, modules/ruxtask/src/vma.rs, ulib/ruxmusl/src/aarch64/mod.rs, ulib/ruxmusl/src/aarch64/syscall_id.rs
When mmap is used for file mapping, write-back operations are performed on a per-page basis, which may change the size of the file.
=> Implement: implement the syscall `ftruncate` and fix the related file mapping problem.

modules/ruxfs/src/root.rs
The following code won't run correctly without this fix
```c
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
/**
* Function to test the rename system call
*
* @param oldname Original filename
* @param newname New filename
* @return 0 on success, -1 on failure
*/
int test_rename(const char *oldname, const char *newname)
{
// Create test file
int fd = open(oldname, O_CREAT | O_WRONLY, 0644);
if (fd == -1) {
perror("Failed to create test file");
return -1;
}
close(fd);
printf("Test file created: %s\n", oldname);
// Attempt to rename file
if (rename(oldname, newname) == -1) {
perror("rename() call failed");
unlink(oldname); // Clean up test file
return -1;
}
printf("Successfully renamed %s to %s\n", oldname, newname);
// …
```
=> fix(rename): correctly handle rename in struct RootDirectory

CHANGELOG.md, README.md
=> Merge dev into main
